### ISSUE TITLE
Remove boost and add CMake

### ISSUE THREAD

**Issue by naveenvhegde** [anandkulkarnisg/countDownLatch#1]

**Comment by anandkulkarnisg** [comment]
1. - boost::noncopyable removal i will adopt. Agree better to use explicit deletion of 
     unwanted construction.

2. I want you to change cmake so that it buids a .so file for countdownLatch and then links it 
  against the examples using -lCountDownLatch [ libCountDownLatch.so ]. 

Please provide the patch / merge. I will review and incorporate.

**Comment by naveenvhegde** [comment]
@anandkulkarnisg Sure. will do and update the PR.

**Comment by naveenvhegde** [comment]
@anandkulkarnisg You can find cmake to generate .so file under commit https://github.com/anandkulkarnisg/countDownLatch/pull/2/commits/9e0684a38a2aca42087be7358eb02086a77ce299

**Comment by anandkulkarnisg** [comment]
done - completed.
