### ISSUE TITLE
Wonder about CountDownLatch.await_for ?

### ISSUE THREAD

**Issue by john-Ly** [anandkulkarnisg/countDownLatch#3]
https://github.com/anandkulkarnisg/countDownLatch/blob/2cfa6fac45950caace8c56b5b36fcddba8702172/CountDownLatch.cpp#L30

Are there some drawbacks of this implementation ? I run example2.cpp, this works.
So, can you tell me the reason about this? Thx.

**Comment by anandkulkarnisg** [comment]
The wait for is a Java conformant implementation. There are cases where you do not want to wait indefinitely and want to come out. else this will become blocker for execution. its like timeout for wait feature of the latch. iso cpp guys don't like this feature. Hence I did it to make same Java feature available to c++ guys.

**Comment by anandkulkarnisg** [comment]
I forgot to remove that comment line from the code. Actually the wait feature works perfectly now. So I can remove it perhaps. Does that answer your question ? If so I can close the issue.

**Comment by john-Ly** [comment]
Ok, i understand.
But, i have another question: since m_count is already thread-safe, why use the read_lock(share_lock) again? I know that it can provide more parallel read operation. (and i noticed the comment when you declare m_count with atomic<long>). I just have no idea. Can i replace it with regular integer protected by lock stuff?

**Comment by anandkulkarnisg** [comment]
The answer is a bit involved and detailed.

1. Yes m_count and m_status are both threadsafe since they are atomic, that is why you can see the   
     thread running the countdown() function is rightly not using any locks.

2. The reason for lock arises from the requirement of signal coordination between threads that do count 
    down and the thread(s) that are awaiting using await function. Without a lock, the m_cond_any won't 
    work.

3. Why I choose shared_mutex and m_cond_any rather than mutex and m_cond. The reason is precisely 
    the functions toString() and getCount(). They require the status of the latch as precisely as possible. 
    i.e when they are executed [ mostly for debug purpose ] until their execution completes we at least want 
    to make sure we give an accurate picture of the latch. So if latch count goes down to zero and we are 
    executing the toString() method then the other threads waiting on m_cond_any will not get a lock to 
    exit out but they can do so only after the read Lock is destroyed at the end of either the toString() or 
    getCount() method.

4. Since I need both read and write style lock for design the choice of shared_mutex becomes imminent.
   And m_cond_any is required as m_cond won't work with shared_mutex [ it only works with mutex ]

Yes, You can redesign the latch using normal variables also but I preferred to design this way. Trying to use the best of both worlds. The Java design requires that the status of latch must remain as consistent as possible during execution of status reading functions like getString() and getCount() [ Else debugging 
the race conditions and other highly concurrent scenarios become hard ]

**Comment by john-Ly** [comment]
Oh, thanks for the reply. I am studying the concurrency in c++ now, so ask a lot.
Again, thank for your time.
This issue can be closed. :)

**Comment by anandkulkarnisg** [comment]
nps , enjoy getting locked into threading and learning.
